[[lab7]]
= Lab 7: {lab7-title}

== Prerequisites

Windows `spring-cloud-dataflow-server-local` and `spring-cloud-dataflow-shell` started and in the last status of the previous lab.

== Steps

Inside `spring-cloud-dataflow-shell.bat` window, I typed the following command:

----
app import --uri http://bit.ly/Celsius-SR1-stream-applications-rabbit-maven
----

The output of this command was the showed bellow.
I saw that a lot of applications (65) were registered:

----
Successfully registered 65 applications from [source.sftp, source.mqtt.metadata, sink.mqtt.metadata, source.file.metadata, processor.tcp-client, source.s3.metadata, source.jms, source.ftp, processor.transform.metadata, source.time, sink.mqtt, sink.s3.metadata, processor.scriptable-transform, sink.log, source.load-generator, processor.transform, source.syslog, sink.websocket.metadata, sink.task-launcher-local.metadata, source.loggregator.metadata, source.s3, source.load-generator.metadata, processor.pmml.metadata, source.loggregator, source.tcp.metadata, processor.httpclient.metadata, sink.file.metadata, source.triggertask, source.twitterstream, source.gemfire-cq.metadata, processor.aggregator.metadata, source.mongodb, source.time.metadata, source.gemfire-cq, sink.counter.metadata, source.http, sink.tcp.metadata, sink.pgcopy.metadata, source.rabbit, sink.task-launcher-yarn, source.jms.metadata, sink.gemfire.metadata, sink.cassandra.metadata, processor.tcp-client.metadata, processor.header-enricher, sink.throughput, sink.task-launcher-local, processor.python-http, sink.aggregate-counter.metadata, sink.mongodb, processor.twitter-sentiment, sink.log.metadata, processor.splitter, sink.hdfs-dataset, source.tcp, processor.python-jython.metadata, source.trigger, source.mongodb.metadata, processor.bridge, source.http.metadata, source.rabbit.metadata, sink.ftp, sink.jdbc, source.jdbc.metadata, source.mqtt, processor.pmml, sink.aggregate-counter, sink.rabbit.metadata, processor.python-jython, sink.router.metadata, sink.cassandra, processor.filter.metadata, source.tcp-client.metadata, processor.header-enricher.metadata, processor.groovy-transform, source.ftp.metadata, sink.router, sink.redis-pubsub, source.tcp-client, processor.httpclient, sink.file, sink.websocket, source.syslog.metadata, sink.s3, sink.counter, sink.rabbit, processor.filter, source.trigger.metadata, source.mail.metadata, sink.gpfdist.metadata, sink.pgcopy, processor.python-http.metadata, sink.jdbc.metadata, sink.gpfdist, sink.ftp.metadata, processor.splitter.metadata, sink.sftp, sink.field-value-counter, processor.groovy-filter.metadata, processor.twitter-sentiment.metadata, source.triggertask.metadata, sink.hdfs, processor.groovy-filter, sink.redis-pubsub.metadata, source.sftp.metadata, processor.bridge.metadata, sink.field-value-counter.metadata, processor.groovy-transform.metadata, processor.aggregator, sink.sftp.metadata, processor.tensorflow.metadata, sink.throughput.metadata, sink.hdfs-dataset.metadata, sink.tcp, source.mail, sink.task-launcher-cloudfoundry.metadata, source.gemfire.metadata, processor.tensorflow, source.jdbc, sink.task-launcher-yarn.metadata, sink.gemfire, source.gemfire, source.twitterstream.metadata, sink.hdfs.metadata, processor.tasklaunchrequest-transform, sink.task-launcher-cloudfoundry, source.file, sink.mongodb.metadata, processor.tasklaunchrequest-transform.metadata, processor.scriptable-transform.metadata]
----

All these aplications could also be viewed in the dashboard (http://localhost:9393/dashboard).

== Notes/conclusions

After the registration, the applications were stored in my local maven repository (the `~/.m2` directory).

[TIP]
====
I could check this information by typing the following command:

----
$ find ~/.m2/repository/org/springframework/cloud/stream -type f -name '*.jar' | wc -l
      65
----
====

I could customize the applications that I want to install by creating a properties file.

For example, I could type the following commands to save and edit a `apps.properties` file only with the contents I would like to have:

----
curl -L http://bit.ly/Celsius-SR1-stream-applications-rabbit-maven > apps.properties
vim apps.properties
----

By doing this I could specify which sources, sinks, processors, and tasks, that I want to deploy.

I could also customize the maven repository used to download these applications.
To do this I only need to specify a property like in following command:

----
java -jar spring-cloud-dataflow-server-local-1.4.0.RELEASE.jar --maven.remote-repositories.repo1.url=http://nexus.example.com/repository/maven-central/
----
